### ISSUE TITLE
Unable to send emails through Office365

### ISSUE THREAD

**Issue by johngayler** [rich-iannone/blastula#1]
When attempting to send emails through Office365, using either POP, IMAP or SMTP settings, the following error message is returned in the console.

`Error: EmailException (Java): Sending the email to the following server failed : smtp.office365.com:465`

Port 465 is always attached to the end of the server, regardless of the value entered for the `port` argument of  `send_email_out`.

**Comment by rich-iannone** [comment]
@johngayler I've just pushed a change to enable the use of TLS for the SMTP server. I believe this must be set to TRUE for `smtp.office365.com`. There's the option to set this in the credentials file or in the `send_email_out()` function.

I've also added a `debug` argument in the `send_email_out()` function. Set this to TRUE and this can help diagnose the port setting issue. Essentially, debug messages will be printed to the console. If you still cannot send messages, provide some of the function call and the console output (obviously, no usernames or passwords).

**Comment by johngayler** [comment]
Thanks @rich-iannone, I'm now able to send via SMTP.

**Comment by rich-iannone** [comment]
Awesome! I'll close now.

**Comment by bennlich** [comment]
What's the difference between `send_email_out` and `smtp_send`? Looking at the source, it seems like `send_email_out` supports tls, but `smtp_send` does not.

**Comment by rich-iannone** [comment]
@bennlich `send_email_out()` is no longer in `master`. It's been phased out in favor of `smtp_send()`.

**Comment by bennlich** [comment]
@rich-iannone aha. Does smtp_send support TLS? I think that might be necessary to work with outlook mail servers.

**Comment by bennlich** [comment]
Nevermind! mailsend-go (and thus `smtp_send`) supports TLS by passing `use_ssl = FALSE`.
