### ISSUE TITLE
cannot add images

### ISSUE THREAD

**Issue by enricodata** [rich-iannone/blastula#110]
when I try to reproduce the example from the documentation:
img_file_path <-
  system.file(
    "img", "myimage.jpeg",
    package = "blastula"
  )

img_string <- add_image(file = img_file_path)

then I get the following error:
"Error in readBin(con = file, what = "raw", n = file.info(file)$size) : can only read from a binary connection"

And if I add an image with the following:
img_file_html <-add_image(file = "myimage.png") 

email <-
  compose_email(
    body = "test image 
 {img_file_html}
")

then the image in the email looks like this:
<img cid="rekjmgfqcvbn__myimage.png" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAAAXNSR0IArs4c6QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAAL3VJREFUeAG9fAmcXFWZ71e39r16S3c66XRnIZ2QhLCExbAkAQkPwmMUEHFGFBgmOsO48FPfE+... zT3q3O8z2t5BRW75kWXa0cxgFzhIuzlse72nvOujStK5rb/zbvR6f+/3HNpx/4F7IvUkTUWyM7xwDFvDWST99vB//H9FiTBFSQfeLAAAAAElFTkSuQmCC" width="520" alt=""/>

What should I do to send images in the email?

**Comment by enricodata** [comment]
I solved it by adding the image as a link. But I still wonder why the above does not work. Maybe because I am using mailgun?

**Comment by sid5150** [comment]
Still getting the same error
