### ISSUE TITLE
Can we use animated gifs or animated PNGs in email messages

### ISSUE THREAD

**Issue by charlesatkinson2000** [rich-iannone/blastula#121]
Just curious if this is possible. It would be phenomenal if it were so.

Also, if this can currently be done, could you provide some examples?

Thanks!

**Comment by rich-iannone** [comment]
I'm pretty sure that animated gifs are possible to add in and that they'll display properly in the more modern email clients. Not entirely sure about the animated PNGs however. I will report back once this is verified. Thanks!
