### ISSUE TITLE
email showing @media codes

### ISSUE THREAD

**Issue by stewartli** [rich-iannone/blastula#124]
I am not able to send gmail out although I tried all sorts of ways. When I send from outlook to gmail, the email was received sucessfully. But the received gmail contains many css codes such as @media ... Don't know what made that. Please help. Thank you.   
![image](https://user-images.githubusercontent.com/35153517/70294180-8b7a1580-1847-11ea-81e3-8b071ce4d23e.png)

**Comment by stewartli** [comment]
Others asked

**Comment by JohnCoene** [comment]
I see that too

**Comment by JohnCoene** [comment]
This seems to be similar to #93

**Comment by rich-iannone** [comment]
@JohnCoene @stewartli We made fixes for this issue but we'd like to make sure the fixes work on your system. Could you confirm, after updating to the latest version of `master`, that the issue is resolved? We would really appreciate this, thanks!
