### ISSUE TITLE
Issue with Htmlwidgets for R

### ISSUE THREAD

**Issue by palmierieugenio** [rich-iannone/blastula#125]
I am trying to use it to send mails that include  [Htmlwidgets ](https://www.htmlwidgets.org/) for R, but it doesn't show the output:

`
```
output: blastula::blastula_email 
```

```{r}
library(leaflet)
data(quakes)

# Show first 20 rows from the `quakes` dataset
leaflet(data = quakes[1:20,]) %>% addTiles() %>%
  addMarkers(~long, ~lat, popup = ~as.character(mag), label = ~as.character(mag))
```

```{r}
library(dygraphs)
lungDeaths <- cbind(mdeaths, fdeaths)
dygraph(lungDeaths)
```

`

Is it possible to include html widgets? If not, I suggest you to try to include this option, if possible.

**Comment by ifellows** [comment]
I don't think this is possible. It is my understanding that e-mail clients do not generally execute javascript.

**Comment by rich-iannone** [comment]
That’s right. We can’t expect any htmlwidgets to work when emailed.
