### ISSUE TITLE
libssl.so.35 not being found (symbolic link broken?)

### ISSUE THREAD

**Issue by vfulco** [rich-iannone/blastula#13]
Not terribly facile with inner guts of linux and symbolic links.  Running daily build of Ubuntu 18.04 (bionic beaver) and latest R, R-studio, blastula and all packages.

/home/foo_user/foo_script/mailsend: error while loading shared libraries: libssl.so.35: cannot open shared object file: No such file or directory
Error in system(command = command, intern = TRUE) : 
  error in running command

libssl1.1 and *-dev are installed.

libssl-dev is already the newest version (1.1.0g-2ubuntu3).

Will post here if I solve.

**Comment by mvellinger** [comment]
Seconding this. This is actually breaking and no public release other than the truly ancient v0.1 is available.

**Comment by raubreywhite** [comment]
Me too

**Comment by simsonas** [comment]
I am having this issue also on Ubuntu 16.04, is there any workaround available?

**Comment by simsonas** [comment]
Creating links with specific names is a quick workaround that worked for me:

```
sudo ln -s /lib/x86_64-linux-gnu/libssl.so.1.0.0 /lib/x86_64-linux-gnu/libssl.so.35
sudo ln -s /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/libcrypto.so.35
```

**Comment by shizidushu** [comment]
@simsonas I have the same problem. But there is no file described as `/lib/x86_64-linux-gnu/libssl.so.1.0.0` in the directory.
