### ISSUE TITLE
The emails sent from Blastula 0.31 arrive with a long paragraph of code. 

### ISSUE THREAD

**Issue by apalacio10** [rich-iannone/blastula#140]
![Captura de Pantalla 2020-01-14 a la(s) 10 55 22 p  m](https://user-images.githubusercontent.com/40868159/72403671-f9580d80-3720-11ea-964d-583234a4b45f.png)

**Comment by Alternikaner** [comment]
Duplicate of #93

**Comment by rich-iannone** [comment]
Now fixed by #153
