### ISSUE TITLE
Adding params

### ISSUE THREAD

**Issue by sobradob** [rich-iannone/blastula#141]
Thanks for the project. 

A key difference between `blastula::render_email` and `rmarkdown::render` is that the latter accepts params, and the former does not. 

Would it be very complicated to pass on the argument from one to the other?

**Comment by jdbarillas** [comment]
If you're using the most recent CRAN release, you should be able to specify these using the `render_options` argument in `render_email`, see the documentation (https://rich-iannone.github.io/blastula/reference/render_email.html)

```
render_email(input, envir = parent.frame(), quiet = TRUE,
  output_options = list(), render_options = list(params = list(# params here)))
```

**Comment by sobradob** [comment]
Excellent, thanks! I was trying to pass on `params = list()` to the function directly.
