### ISSUE TITLE
'Login denied' on use of `smtp_send()` with gmail

### ISSUE THREAD

**Issue by cawthm** [rich-iannone/blastula#143]
I've scoured the issues thread here (including #127), having initially followed [this article's directions on configuring google to allow less secure apps](https://cran.r-project.org/web/packages/blastula/vignettes/sending_using_smtp.html).  

<img width="420" alt="image" src="https://user-images.githubusercontent.com/1149250/73466015-dfd0db80-4346-11ea-98b2-0bc39f764ba3.png">

My gmail security was switched 36+ hours ago as shown in the above screenshot, and yet I get the following error when using  `smtp_send()` (after having duly created a credentials file)

```
create_smtp_creds_file(file = "my_creds",
                       user = "my_email@example.com",
                       provider = "gmail")

## enter gmail password in popup

compose_email(body) %>% smtp_send(to = "another_email@example.com",
                    from = "my_email@example.com",
                    subject = "Test",
                    credentials = creds_file("my_creds"))
```
`Error in curl::curl_fetch_memory(url, handle = h) : Login denied`

Am I missing something with the google config steps, or might the error be elsewhere?

And thank you, btw, for this very useful package.

**Comment by cawthm** [comment]
Ok...I just realized that there's the admin level ("allow users to manage..."), and the user level.

So my issue is solved.

**Comment by gueyenono** [comment]
> Ok...I just realized that there's the admin level ("allow users to manage..."), and the user level.
> 
> So my issue is solved.

Would you please share how you found the admin level? I can't seem to find it. I am having the same issue.
