### ISSUE TITLE
Width of e-mail using render_connect_email

### ISSUE THREAD

**Issue by iainmwallace** [rich-iannone/blastula#144]
Hi,

I am finding that the width of the email rendered using the "render_connect_email" is very narrow in my outlook client. This adversely affects tables in the email 

Is there any way of modifying it? 

Thanks

Iain

**Comment by winstonwhe** [comment]
Hi Iain,

one solution I've found is adding a little css after my yaml header.

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

I hope that helps as a partial solution in the meantime.

**Comment by rich-iannone** [comment]
Fixed in #178
