### ISSUE TITLE
feature-request - password as function parameter

### ISSUE THREAD

**Issue by mraess** [rich-iannone/blastula#149]
Hey is there any way to make it so smtp passwords can be supplied to the function directly/ That way local sending or sending on RS Connect via environment variables would become possible without having to manually enter the password into the prompt.

**Comment by rich-iannone** [comment]
Thanks for the suggestion. We feel it's unsafe to supply the password directly, but, it's worth making a `creds_envvar()` that allows you to supply password info (and possibly other config params) through environment variables.

**Comment by mraess** [comment]
Hey, yeah that would be awesome - I'm trying to use the package on RStudio Connect and need to be able to supply passwords via Sys.getenv() as environment variables.

**Comment by rich-iannone** [comment]
@mraess Thanks for the suggested feature. It's implemented now in `master`.

**Comment by mraess** [comment]
Awesome! Thanks
