### ISSUE TITLE
evaluation of local variables needs .envir

### ISSUE THREAD

**Issue by aronatkins** [rich-iannone/blastula#15]
Given the following R script:

```r
library(blastula)

doit <- function() {
  importantPerson <- "Bob"
  message <- blastula::compose_email(
    'you are quite important, {importantPerson}'
  )
  body_html <- blastula::get_html_str(message)
  body_html
}

doit()
```

Running with `Rscript minimal.R` produces an evaluation error:

```
Error in eval(parse(text = code, keep.source = FALSE), envir) :
  object 'importantPerson' not found
Calls: doit ... glue_data -> <Anonymous> -> .transformer -> eval -> eval
Execution halted
```

There are two workarounds:
1. Move the definition of `importantPerson` to the global environment.
2. Add the argument `.envir = new.env()` to the `compose_email` arguments.

This latter workaround feels like it should be the default; instructing `glue::glue` to use the calling environment when evaluating template strings.

This same issue is encountered when embedding blastula rendering within an R Markdown document:

````
---
title: this email is so custom
---
```{r}
library(blastula)
importantPerson <- "Bob"
message <- blastula::compose_email(
  'you are quite important, {importantPerson}'
)
body_html <- blastula::get_html_str(message)
body_html
```
````

**Comment by rich-iannone** [comment]
This is now fixed by adding `.envir = parent.frame()` to the `compose_email()` argument list. The `.envir` is passed to each relevant `glue::glue()` call.
