### ISSUE TITLE
Feature suggestion: add argument to `compose_email` in order to add ad-hoc CSS customizations

### ISSUE THREAD

**Issue by adisarid** [rich-iannone/blastula#152]
I would like to take advantage of the nice format which `compose_email` provides, but with slight variations, e.g., text direction from right to left (`direction:rtl;`) for relevant languages (but can easily be any other css for that matter).

Would be nice to have it as an added argument of the `compose_email` function for ad-hoc css addition to the regular css chunk this function provides.

The approach I tried manually was using `str_replace` on the `email$html_str` and/or `email$html_html`. Didn't work for me unfortunately. Note that the following example is with the text-align property (easier to spot than the direction property which I referred to previously).

```
library(stringr)
library(blastula)
body <- md("# This is

A test
For right-aligned text."
)

email <- compose_email(title = "test",
                       body = body)

email$html_str <- str_replace_all(email$html_str, pattern = '<body>',
                                  replacement = '<body style="text-align:right;"')
email$html_html <- str_replace_all(email$html_html, pattern = '<body>',
                                   replacement = '<body style="text-align:right;"')

```

**Comment by zacdav** [comment]
I was looking into modifying css for a separate reason and found some odd behaviour.
Try this:

```
library(stringr)
library(blastula)
library(glue)

body <- md("# This is

A test
For right-aligned text."
)

email <- compose_email(title = "test", body = body)
additional_body_styles <- "text-align:right;"

email$html_str <- gsub('body style="(.*?)">', glue('body style="\\1{additional_body_styles}'), email$html_str)
email$html_html <- email$html_str  %>% htmltools::HTML()
email
```

**Comment by adisarid** [comment]
@zacdav , you're awesome.
This works. 
I wonder if we should we do a PR for a function which does this... (would like to or should I?)

**Comment by zacdav** [comment]
It could be made a separate function. I expect this would be most useful if you can add css to existing blocks - not just the body.

So candidates would probably be adjusting blastula:::render_blocks() and the functions it calls within, and maybe all the other "blocks" functions?

I expect @rich-iannone would have a better idea, given he wrote the package, I have only tinkered with this for 30 minutes.

**Comment by adisarid** [comment]
Perhaps something like

```
update_tag_css <- function(email, tag = "body", new_css){
  
  email$html_str <- gsub(paste0(tag, ' style="(.*?)">'), 
                                glue(paste0(tag, ' style="\\1{new_css}"')), 
                         email$html_str)
  
  email$html_html <- email$html_str %>% htmltools::HTML()
  
  email
  
}
```

**Comment by rich-iannone** [comment]
When https://github.com/rich-iannone/blastula/pull/178 is merged, you'll have the ability to define an entire template for `compose_email()`, using its `template` argument.
