### ISSUE TITLE
add_attachment with smtp_send does not work

### ISSUE THREAD

**Issue by Neo005** [rich-iannone/blastula#155]
add_attachment with smtp_send does not work - the below example - email gets sent but attachment file (XYZ.csv) which is in the same directory does not get sent

file = "XYZ.csv"

email <- render_email('ABC.Rmd')

add_attachment(email, file , content_type = mime::guess_type(file)) 

  email %>%
  smtp_send(
    from = "jack@email.com",
    to = c("junior@email.com"),
    subject = paste0("Hello ",Sys.Date(),":"),
    credentials = creds_anonymous(host = "wmail.abc.com",port=25, use_ssl = FALSE)
    
  )

**Comment by rich-iannone** [comment]
Hi @Neo005 , it looks like there is a slight error in the code. The call to `add_attachment()` doesn't reassign its output to `email` so the last `smtp_send()` call won't include the attachment. The corrected code is:

```r
file = "XYZ.csv"

email <- render_email('ABC.Rmd')

email <- add_attachment(email, file , content_type = mime::guess_type(file))

email %>%
  smtp_send(
    from = "jack@email.com",
    to = c("junior@email.com"),
    subject = paste0("Hello ", Sys.Date(), ":"),
    credentials = creds_anonymous(host = "wmail.abc.com", port = 25, use_ssl = FALSE)
  )
```
