### ISSUE TITLE
FR: Reply to or forward an email

### ISSUE THREAD

**Issue by iago-pssjd** [rich-iannone/blastula#163]
I am not sure it is a possibility, but if not it would be an interesting feature to have the possibility of reply emails and also forwarding them.

Thank you!

**Comment by rich-iannone** [comment]
I think this feature may be a little out of scope for this package, where the intent is to be a great emailer (but not a mail client). 

However there is the gmailr package (https://github.com/r-lib/gmailr) which has this functionality now (with Gmail), should you need it.
