### ISSUE TITLE
Gibberish HTML on Outlook365

### ISSUE THREAD

**Issue by leungi** [rich-iannone/blastula#167]
Hi, 

I'd looked at #161, #162 and #153, but still facing similar issue.

#### Reprex
```r
library(blastula)

test_message <- prepare_test_message()

test_message %>%
  smtp_send(
    from = "ivan@company.com",
    to ="ivan@company.com",
    subject = "Testing the `smtp_send()` function",
    credentials = creds(
      user = "ivan@company.com",
      host = "smtp.company.com",
      port = 25,
      use_ssl = FALSE
    )
  )
```

#### Package info
```r
> packageVersion("blastula")
[1] ‘0.3.1.9000’

> desc::desc_get_field(
      "GithubSHA1",
      file = system.file("DESCRIPTION", package = "blastula")
  )
[1] "9998e41dca776eb4d35199f0f61ec48d8693f306"
```

#### Mime file
```r
> test_message %>%
   blastula:::generate_rfc2822() %>%
   cat(file = "mime.txt")
```

[mime.txt](https://github.com/rich-iannone/blastula/files/4442034/mime.txt)

Look forward to guidance; thanks!

**Comment by MadhulikaTanuboddi** [comment]
@leungi : I tried your example on Windows and the email looks good on Outlook desktop client . It looks like your blastula package is at an older SHA1. Can you try installing the latest of the package from git and check if the issue still happens?
```
install.packages("devtools")
devtools::install_github("rich-iannone/blastula")
```

**Comment by rich-iannone** [comment]
Going to assume this is fine because we got responses from others reporting that the fix was successful. Closing.

**Comment by leungi** [comment]
Thanks for prompt update @rich-iannone 🙏

It works as designed; awesome 🙌

For future me: pulled from `rich-iannone-blastula-da2b1cb` commit.

![image](https://user-images.githubusercontent.com/30273868/79943713-3d992f00-842f-11ea-9408-635692fe62eb.png)

**Comment by rich-iannone** [comment]
@leungi Excellent!
