### ISSUE TITLE
Where i can add HTML block in compose_email()

### ISSUE THREAD

**Issue by selesnow** [rich-iannone/blastula#168]
Hello!

Earlier i creating html table by `kableExtra` and add block with this table:

```
html_table <- kable(...)
current_date_time <- add_readable_time()
  
  email <- compose_email(body =
                           blocks(
                             add_image(file = "black.png"),
                             block_text( paste0("**TITLE**")), 
                             block_text("Any text."),
                             block_text(html_table )
                           ), 
                         footer = "Send at {current_date_time}")
```

Now i get error: `Error: The input text must be of class "character"`.

And now does`t work markdown formatting.

Can you help me?

**Comment by rich-iannone** [comment]
Hi, to make this work you have to ensure that the HTML table is transformed to an HTML string. After getting `html_table` as a length 1 character vector, you can use this:

```r
compose_email(
  body =
    blocks(
      block_text(md(html_tbl))
    )
)
```

Having the `md()` is required to ensure that the HTML is passed through without any escaping. Let me know if this works out for you.

**Comment by selesnow** [comment]
Hello, thanx.

For me works `block_text(md(as.character(html_tbl)))`.

**Comment by rich-iannone** [comment]
The `as.character()` part transforms the table to an HTML string and changes the class to `character`. Glad that this is now working for you. Will close the issue now.

**Comment by munoztd0** [comment]
This still removes all the formatting of the html table unfortunately..
