### ISSUE TITLE
httr should not be a required dependency

### ISSUE THREAD

**Issue by aronatkins** [rich-iannone/blastula#18]
The `httr` dependency is only used by `send_by_mailgun` and not needed in many uses of the `blastula` package.

**Comment by rich-iannone** [comment]
@aronatkins Yeah, should have moved this to `Suggests` a long time ago but I'll definitely do this next.

**Comment by rich-iannone** [comment]
@aronatkins **httr** is now a suggested package. I'll submit the package to CRAN shortly.
