### ISSUE TITLE
Are there ways to modify the looks of the emails for them to look wider

### ISSUE THREAD

**Issue by statquant** [rich-iannone/blastula#187]
Hello, thanks for this package.
I am planing to use it and I have been tested it a bit. My issue is that I receive in outlook those emails and they look terribly "narrow" to me.
Is there anything I can do to tune the looks a bit wider ? I noticed the package ships with a template.html file that I was thinking to copy, change, and pass to output_options.
Thanks and regards

**Comment by rich-iannone** [comment]
This has been addressed in https://github.com/rich-iannone/blastula/pull/178. If you install the development version of blastula, you’ll be able to try out the new, wider default template.
