### ISSUE TITLE
Compose email crashes unless a line break is specified

### ISSUE THREAD

**Issue by nwstephens** [rich-iannone/blastula#19]
When I use `compose_email` with `add_ggplot` and `formattable` sometimes my session crashes. I say sometimes, because it appears to depend on the size of the ggplot and the platform. I was not able to reproduce the error on my desktop, but I was able to reproduce it on RSP.

The problem occurs when I include a plot and a table in `compose_email`:

```
compose_email("Hello! {add_ggplot(myplot)} {formattable(head(mytable))}")
```

![image](https://user-images.githubusercontent.com/7519295/47814482-3a365300-dd24-11e8-9722-81c293038345.png)

I would not expect this code to unexpectedly crash my session. Instead I would expect it to produce an email with a plot and a table. I found that if explicitly called for a line break, then the code will work:

```
compose_email("Hello! {add_ggplot(myplot)} \n {formattable(head(mytable))}")
```

The `\n` line break must be explicit. If I use carriage returns without the line break, I get the same error above. If I remove either the plot or the table, I do not get an error. But if I leave out `\n` then my session crashes for this particular plot and table on RSP. I think the code should not require an explicit line break.

**Comment by rich-iannone** [comment]
@nwstephens I couldn't reproduce the error but I don't doubt it exists. I'm using the GitHub version of **blastula** and the CRAN versions of **ggplot2** and **formattable**.  I used the following code on both Mac and Linux (Ubuntu 18.04) builds of RStudio:

```r
library(blastula)
library(ggplot2)
library(formattable)

df <- data.frame(
  id = 1:10,
  name = c("Bob", "Ashley", "James", "David", "Jenny", 
           "Hans", "Leo", "John", "Emily", "Lee"), 
  age = c(28, 27, 30, 28, 29, 29, 27, 27, 31, 30),
  grade = c("C", "A", "A", "C", "B", "B", "B", "A", "C", "C"),
  test1_score = c(8.9, 9.5, 9.6, 8.9, 9.1, 9.3, 9.3, 9.9, 8.5, 8.6),
  test2_score = c(9.1, 9.1, 9.2, 9.1, 8.9, 8.5, 9.2, 9.3, 9.1, 8.8),
  final_score = c(9, 9.3, 9.4, 9, 9, 8.9, 9.25, 9.6, 8.8, 8.7),
  registered = c(TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
  stringsAsFactors = FALSE)

# Create an HTML table with `format_table()`
formatted_table <-
  formattable(df, list(
    age = color_tile("white", "orange"),
    grade = formatter("span", style = x ~ ifelse(x == "A", 
                                                 style(color = "green", font.weight = "bold"), NA)),
    area(col = c(test1_score, test2_score)) ~ normalize_bar("pink", 0.2),
    final_score = formatter("span",
                            style = x ~ style(color = ifelse(rank(-x) <= 3, "green", "gray")),
                            x ~ sprintf("%.2f (rank: %02d)", x, rank(-x))),
    registered = formatter("span",
                           style = x ~ style(color = ifelse(x, "green", "red")),
                           x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))
  ))

# Create a ggplot plot object
plot <- 
  ggplot(
    data = mtcars,
    aes(
      x = disp, y = hp,
      color = wt, size = mpg)) +
  geom_point()

email <- compose_email("Hello! {add_ggplot(plot)} {formattable(head(formatted_table))}")

preview_email(email)
```

And didn't have any problems with the R session. Could we have a video call soon so I could see the issue from your computer?
