### ISSUE TITLE
SMTP authentication issue with SendGrid

### ISSUE THREAD

**Issue by jonmcalder** [rich-iannone/blastula#20]
When trying to send with SendGrid via `blastula`:

```
send_email_out(
    message = email_object,
    from = <from>,
    to = <to>,
    subject = <subject>,
    sender = <sender>
    host = "smtp.sendgrid.net",
    port = 465,
    user =  <user>,
    password = <password>,
    use_ssl = TRUE,
    authenticate = TRUE
)
```

I get an authentication error:

> Error: AUTH LOGIN failed: '535 Authentication failed: The provided authorization grant is invalid, expired, or revoked'

Initially I thought it was due to incorrect credentials for SendGrid's SMTP relay, but I have since verified repeatedly that the exact same details (host, port, user & password) work fine when trying with the `mailR` package:

```
library(mailR)

send.mail(
    from = <from>,
    to = <to>
    subject= <subject>,
    body = <body>,
    smtp = list(
        host.name = "smtp.sendgrid.net", 
        port = 465, 
        user.name= <user>, 
        passwd = <password>, 
        ssl = TRUE
    ),
    authenticate = TRUE,
    send = TRUE
)
```

What am I missing? Any idea what this could be?

**Comment by rich-iannone** [comment]
@jonmcalder sorry for the delay on this. Going to try this out with SendGrid. Also, would it be worth interfacing with the API instead? We have that approach in the `send_by_mailgun()` function (https://github.com/rich-iannone/blastula/blob/master/R/send_by_mailgun.R).

**Comment by jonmcalder** [comment]
No worries - thanks for following up @rich-iannone . 

Yes, interfacing with the API will probably be better in general, although that being said my use case for blastula + SendGrid is mainly for reporting purposes (i.e. small scale & somewhat adhoc) rather than anything resembling a production use case. 

I imagine that for most people (as is the case within my current organisation), any use cases that warrant leveraging the core SendGrid API would usually originate from languages other than R. That being said though, I've been thinking about developing a sendgrid API package for R focussed on the stats/analytics side of things. Made a start on it a while back but haven't really had the time. The only other package I could find is this one: https://github.com/rhochreiter/sendgridR

**Comment by rich-iannone** [comment]
@jonmcalder I'm going to test this again shortly with the new `smtp_send()` function.

**Comment by jonmcalder** [comment]
@rich-iannone Not sure if you got around to testing this again, but I did, and SendGrid works with the new `smtp_send()` function for me, so I'm gonna go ahead and close this. Thanks again!
