### ISSUE TITLE
Apple Mail: Wide images when using add_image

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rich-iannone/blastula#201]
Apple Mail shows wide images when add_image function is used.  The image width always scales to 100% even when a custom width is specified.

```
library(blastula)
library(glue)

# Attribution Information available in `README-attribution.txt`

gt_logo_image <-
  add_image("manual_tests/gt_logo.png", width = "100%")

gt_logo_image_small <-
  add_image("manual_tests/gt_logo.png", width = 150)
```
![Apple_Mail_image_width_not respected](https://user-images.githubusercontent.com/5369655/81622093-f4405d80-93a4-11ea-8db2-9b2153bd0c1e.png)

**Comment by leungi** [comment]
@rich-iannone : the saviour again; just went I was looking for this feature, instead of manually resizing original .png 🙌🙏
