### ISSUE TITLE
Compose email crashes on RHEL

### ISSUE THREAD

**Issue by AhuPersonal** [rich-iannone/blastula#21]
Hi,

compose_email function works well on Mac, but it crashes on RHEL. Is anyone able to work with this function on Rhel ? How can we handle this ?

I already installed and updated the necessary dependencies:

```
sudo yum install openssl-devel
```

**Comment by rich-iannone** [comment]
Let me reproduce this and debug. First need to create a RHEL VM (which is the more time-consuming part).

**Comment by rich-iannone** [comment]
@AhuPersonal could you send a reproducible example that causes the crash? I'm looking into this now and I cannot yeah make an R session crash.
