### ISSUE TITLE
Question: Are tables no longer supported?

### ISSUE THREAD

**Issue by Dreznel** [rich-iannone/blastula#218]
Hello,

I've been trying to figure out how to embed a table into a Blastula email, and I can't figure it out. I have tried using Markdown tables, using HTML directly, and directly copying the code-snippet from #214, but in each case it just prints the literal markdown/HTML text instead of a properly-rendered table.

I see that the [tables example](https://www.rdocumentation.org/packages/blastula/versions/0.2.1) was removed from [the documentation](https://www.rdocumentation.org/packages/blastula/versions/0.3.1). Is this because they are no longer supported?

**Info**: I am currently using Blastula 3.1 on RStudio Server, attempting to send email to a Gmail address.

**Comment by Dreznel** [comment]
Ah my apologies, updating to 0.3.2 fixed the issue. Should have tried that first.

Markdown and HTML tables seem to both work.

Thank you!

**Comment by rich-iannone** [comment]
Just in the middle of writing to you! Okay, this is great to hear.

**Comment by Dreznel** [comment]
One quick update -- my markdown test was inaccurate.  Markdown actually doesn't seem to work:

```
df <- mtcars

## Works
table_to_email <- knitr::kable(
  x = df,
  format = "html"
)

blastula::compose_email(
  body = blastula::md(
    table_to_email
  )
) %>% print()


## Does not work
table_to_email <- knitr::kable(
  x = df,
  format = "markdown"
)

blastula::compose_email(
  body = blastula::md(
    table_to_email
  )
) %>% print()
```

Not a big deal from my end, as using HTML is just as easy, but I don't want to confuse the next person.
