### ISSUE TITLE
Why copy code from package `tools`?

### ISSUE THREAD

**Issue by AshesITR** [rich-iannone/blastula#23]
https://github.com/rich-iannone/blastula/blob/3b69cbcf340be2bba4a9f1d29f6557747668aebf/R/base64.R#L1-L6

This is the same as `tools::file_ext`. Why not use that instead?

**Comment by rich-iannone** [comment]
Good question! But this is now been fixed in https://github.com/rich-iannone/blastula/commit/b6d44622da2b8b9fc71eabf3054cbf504039ad2e. Thanks!
