### ISSUE TITLE
HTML tag appears randomly in html table

### ISSUE THREAD

**Issue by simsonas** [rich-iannone/blastula#25]
Hello,

I am having issue when tag `< td style="text-align:left;"> ` is showing up randomly in html table inside mail body sent by blastula compose_email function. Here is the example:
![image](https://user-images.githubusercontent.com/8759354/53242794-811ece80-36ae-11e9-96e0-d680c34a94e1.png)

Maybe you have some ideas how can I troubleshoot this further?

**Comment by rich-iannone** [comment]
@simsonas could you provide the code that generates the email message body? Then I can better see what is causing the problem (although it looks like a malformed tag right now).

**Comment by simsonas** [comment]
Sure, here is my code:

``` r
test <- kable(ZM_provision, format = "html")
test2 <- kable(Provision_spec_prekes, format = "html")
test3 <- kable(Top20_provision, format = "html")
test4 <- kable(Tiekejai_provision, format = "html")

email_object <- compose_email(body = "irrelevant text **{Dabar_sand_verte}**, Provision vertë: **{Dabar_provision_verte}** *({Provision_proc})*

irrelevant text: \\

{add_ggplot(plot_object = Provison_plot, width = 7, height = 5)} \\
  
irrelevant text: \\
  
{test}\\

<br />

irrelevant text (Top 30):

{test4}\\

<br />
  
irrelevant text:\\
  
{test2}\\

<br />

Top 20 irrelevant text:\\
  
{test3}\\
 
<br />
  ",footer = "irrelevant text: {Sys.time()}")
```

<sup>Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Just to add, this tag is appearing very randomly, I used formattable package and kable function for converting dataframes to html object, it didn't made any difference, also when this tag appears it messes whole email body, it could be aligned right or left.

**Comment by rich-iannone** [comment]
This is not a reproducible example, several objects like `ZM_provision` and `Dabar_sand_verte` are not available. Would you be able to update the example so that it can run anywhere?
