### ISSUE TITLE
text wrapping/image resizing in Google Inbox

### ISSUE THREAD

**Issue by goldingn** [rich-iannone/blastula#3]
Viewing the blastula email you just sent about DiagrammeR revdeps in Google Inbox online, on my laptop (and in Boxy, the client I use), the header image wasn't resized, and long lines of text weren't wrapped (a horizontal scroll bar appeared instead):
![screen shot 2017-08-21 at 10 50 57 am](https://user-images.githubusercontent.com/4450731/29499964-106a4cb0-865f-11e7-9b1f-6b1354c58dff.png)
![screen shot 2017-08-21 at 10 51 09 am](https://user-images.githubusercontent.com/4450731/29499968-1329d470-865f-11e7-8361-0b5dfb00a196.png)

I suspect this is due to the HTML environments that were used. Maybe something like span would make it look nicer?

It looks great on the android Inbox app though.

Not sure show how to make this reproducible, but happy to test out solutions if you want to email them to me!

**Comment by rich-iannone** [comment]
I think this has been solved awhile back. We now automatically set a maximum width for images.
