### ISSUE TITLE
Error in system(command = command, intern = TRUE) :    'CreateProcess' failed

### ISSUE THREAD

**Issue by mark-druffel** [rich-iannone/blastula#36]
I am getting an error when I run send_email_out. Mailsend is a black box to me so I'm uncertain where to go from here, I couldn't find a similar issue on their github page... Any help would be much appreciated!

Thanks,
Mark

Error in system(command = command, intern = TRUE) : 
  'CreateProcess' failed to run 'C:\Users\markd\Desktop\mailsend.exe -from "mdruffel@propellerpdx.com" -name "mdruffel@propellerpdx.com" -t "mdruffel@propellerpdx.com" +cc +bc -sub "Utilization Report"  -starttls  -smtp outlook.office365.com -port 587 -auth -user mdruffel@propellerpdx.com -pass "<my password>"  -mime-type "text/html" -enc-type "us-ascii" -disposition "inline" -attach "message_inlined.html" '

**Comment by Fpadt** [comment]
It looks like I have a similar issue on a Windows OS:

> getwd()
> [1] "C:/tmp"

`send_email_out(
message = email_object,
sender = "Sender Name",
subject = "test 2",
from = "info@gmail.nl",
to = "info@gmail.nl",
creds_file = "c:\\tmp\\gv_fp.cred",
debug = F)`

Error in system(command = command, intern = TRUE) : 
  'C:/tmp/mailsend' not found

> file.exists("C://tmp//mailsend")
> [1] TRUE

**Comment by Fpadt** [comment]
hmm, believe the mailsend is 32-bit and I am running 64. Tried a new version but that also failed however with a different error. Might be the parameters changed

https://github.com/muquit/mailsend/releases

**Comment by rich-iannone** [comment]
Hi @mark-druffel @Fpadt and @vfulco , could you try the new `mailsend-go` approach with the `smtp_send()` function? Installation instructions for `mailsend-go` are in this vignette: https://rich-iannone.github.io/blastula/articles/sending_using_smtp.html.

I'd love to have some feedback on whether this generally solves some of the common issues we've been seeing with email sending.
