### ISSUE TITLE
Argument to add alt text to images

### ISSUE THREAD

**Issue by emilyriederer** [rich-iannone/blastula#39]
Thanks for the great package! I first got to use it last weekend and really enjoyed it, and I've been very excited watching new features flood in this week. I'm hoping to become a heavy user of this package and wanted to share an idea. 

One feature I would appreciate is an optional `alt` argument in `add_image()` and `add_imgur_image()` which could pass a character string to the `alt` attribute of the `<img>` tag. 

Potentially, this could also be used for `add_ggplot()` since that calls `add_image()` internally. Here, perhaps it could be exposed to users but the `alt` text could default to the plot title (if one exists)?

This might be useful for those with bad internet / email clients and make `blastula` emails more accessible to those using screen readers. While not universally supported, I did find some good tables in [this article](https://litmus.com/community/learning/12-alt-text-in-html-email) to suggest that many email clients support `alt` text.

If this sounds like a good idea, I'd be happy to make a PR if that would be helpful.

Thanks again for `blastula`!

**Comment by rich-iannone** [comment]
Thanks for using the package! I think this is a great idea and a PR would be appreciated.

If you like, you could put the `alt` argument in `add_image()` and `add_imgur_image()` in your PR and, for my part, I'll do the same in the new `article()` function.
