### ISSUE TITLE
smtp_send Error in process_initialize Command Not Found

### ISSUE THREAD

**Issue by abesolberg** [rich-iannone/blastula#49]
Hi Rich,
I'm trying to use smtp_send() with the new mail-send-go. I copied both the mailsend-go-dir/mailsend-go.exe into my working directory and when I go to run the command and leave the binary_loc argument empty, I get the message "ERROR: Unknown option ***@**.org" (my from argument) . When I set the binary_loc as my working directory, I get the error message "Error in process_initialize(self, private, command, args, stdin, stdout, : Command not found." 
Thank you!

**Comment by rich-iannone** [comment]
Sorry that you’re experiencing this issue. This function is currently unstable and not well tested in Windows but I do want to get to the bottom of this because it shouldn’t error like this. 

Could you provide the entire function call (leave out any sensitive info of course) that led to the error? Also, could you provide a little more detail on where the mailsend-go binary is located relative to the working directory?

**Comment by abesolberg** [comment]
Of course! Thank you for the quick reply. 

`create_email_creds_file(creds_file_name = ".email_creds" , user = "**@**.org ", password = "password", provider = "outlook" )`

`test_message <- prepare_test_message()`

`blastula:::smtp_send(
  email = test_message,
  from = "charless@camba.org" ,
  to = "charless@camba.org",
  subject = "Testing the smtp_send() function",
  creds_file = ".email_creds" ,
  echo = T ,
  echo_cmd = T
  )`

**Comment by abesolberg** [comment]
`test_message <- prepare_test_message()`

`create_email_creds_file(creds_file_name = ".email_creds" , user = "**@**.org", password = "***", provider = "outlook" )`

`blastula:::smtp_send(
  email = test_message,
  from = "**@**.org" ,
  to = "**@**.org",
  subject = "Testing the smtp_send() function",
  creds_file = ".email_creds" ,
binary_loc = "/mailsend-go-dir" ,
  echo = T ,
  echo_cmd = T
  )`

I've tried a couple different things with the binary (and I've also tried with mailsend-go version 1.0.3 and 1.0.4). First I put the mailsend-go-dir just in my project working directory, and I also extracted everything from that folder into my working directory, and I put just the mailsend-go.exe in the working directory.  

I've tried directing the code there using `binary_loc = getwd()` , and also using `binary_loc = Z:/Path/Project/mailsend-go-dir` and a couple other variations with no luck

**Comment by rich-iannone** [comment]
A solution is in the works to avoid this problem. For an early preview, have a look at the example I posted in https://github.com/rich-iannone/blastula/issues/87.
