### ISSUE TITLE
Use sendmail pkg or mailgun http api

### ISSUE THREAD

**Issue by jeroen** [rich-iannone/blastula#5]
Would be nice to get rid of the Java dependency. The `sendmailR ` package allows for sending email via an aribtrary smtp server, but if you're using mailgun you might as well use their rest api.

**Comment by rich-iannone** [comment]
@jeroen thanks for the idea on using `sendmailR`! Would love to not the user deal with anything Java. So, the next priority for this package is to make this change.

**Comment by peeyooshc** [comment]
I just came across this package and it looks fantastic. One question, any possibility of adding gmailR as a possible sending agent?

**Comment by rich-iannone** [comment]
@jeroen @peeyooshc Just recently removed the strong dependency on **mailR**, **rJava**, etc., and put those (for now) in the `Suggests` list. Main function `send_mail_out()` adopts the more robust implementation without dependencies. Moved the previous function of the same name to `send_by_mailr()`. That will be removed in the future.
