### ISSUE TITLE
E-mail is sent as "inline" attachment instead of regular mail body

### ISSUE THREAD

**Issue by salim-b** [rich-iannone/blastula#55]
Whenever I send an e-mail using `blastula::smtp_send()` the actual message is sent as an "inline attachment" which – at least in Thunderbird 60 with default settings – results in no (visual) text in the mail body unless you [explicitly activate `Display Attachments Inline`](https://kb.wisc.edu/page.php?id=40875).

In the [code of `smtp_send.R`](https://github.com/rich-iannone/blastula/blob/c33786c546c2a6205cc4b7fb43f107528c9266c5/R/smtp_send.R#L250) I see that [mailsend-go's `attach` option](https://github.com/muquit/mailsend-go#synopsis) is used with the `-inline` flag. I guess it would be better to use the `body` option instead (at least by default), so that all mail clients can properly display the message.

Or is there a specific reason why the `attach` option is used?

---

_I'm using the latest dev version of blastula on Ubuntu Linux 16.04 with latest mailsend-go v1.0.4._

**Comment by rich-iannone** [comment]
@salim-b Sorry for the delay in getting back to you on this. Could you send a screenshot of a sample email in Thunderbird 60 that shows the issue?

**Comment by salim-b** [comment]
1. I just realized I'm using the add-on [Thunderbird Conversations](https://addons.thunderbird.net/de/thunderbird/addon/gmail-conversation-view/) (latest version), though it doesn't really make any difference regarding this issue.

    Using this add-on, an e-mail sent by `blastula::smtp_send()` looks by default like this on my system:

    ![1](https://user-images.githubusercontent.com/20040931/60733320-060ed400-9f3c-11e9-92cf-0e857bf76e4c.png)

2. When I deactivate the add-on, an e-mail sent by `blastula::smtp_send()` looks by default like this on my system:

    ![4](https://user-images.githubusercontent.com/20040931/60734922-18d7d780-9f41-11e9-9f52-ffe84d8c9177.png)

3. After enabling Thunderbird's option [`Display Attachments Inline`](https://kb.wisc.edu/page.php?id=40875) **I just discovered another issue (haven't noticed it before): The encoding of the inline attached mail body is not properly auto-discovered!** The mail is displayed in latin-1 instead of the actual UTF-8 encoding:
    
    ![2](https://user-images.githubusercontent.com/20040931/60735176-d793f780-9f41-11e9-8ad3-467a38369622.png)

    The same mail sent using mailsend-go's `body` option displays fine by default:

    ![3](https://user-images.githubusercontent.com/20040931/60735254-1e81ed00-9f42-11e9-9743-91c53bf81fa2.png)

**Comment by salim-b** [comment]
> In the [code of `smtp_send.R`](https://github.com/rich-iannone/blastula/blob/c33786c546c2a6205cc4b7fb43f107528c9266c5/R/smtp_send.R#L250) I see that [mailsend-go's `attach` option](https://github.com/muquit/mailsend-go#synopsis) is used with the `-inline` flag. I guess it would be better to use the `body` option instead (at least by default), so that all mail clients can properly display the message.

To be more clear: Instead of this code 

```r
  run_args <-
    list(
      `-sub` = subject,
      `-smtp` = credentials$host,
      `-port` = credentials$port %>% as.character(),
      `-ssl` = ssl_opt,
      `auth` = no_options(),
      `-user` = credentials$user,
      `-pass` = credentials$password,
      `-fname` = sender_name_opt,
      `-from` = from,
      `-to` = to,
      `-cc` = cc,
      `-bcc` = bcc,
      `attach` = no_options(),
      `-file` = tempfile_,
      `-mime-type` = "text/html",
      `-inline` = no_options()
    )
```

I would suggest to use this (at least by default):

```r
  run_args <-
    list(
      `-sub` = subject,
      `-smtp` = credentials$host,
      `-port` = credentials$port %>% as.character(),
      `-ssl` = ssl_opt,
      `auth` = no_options(),
      `-user` = credentials$user,
      `-pass` = credentials$password,
      `-fname` = sender_name_opt,
      `-from` = from,
      `-to` = to,
      `-cc` = cc,
      `-bcc` = bcc,
      `body` = no_options(),
      `-file` = tempfile_,
      `-mime-type` = "text/html"
    )
```

**Comment by fmichonneau** [comment]
I did a quick test and I can confirm that using the `body` option to pass the HTML file for the email instead of using `attach` displays the email correctly instead of showing an empty message with an attachment.
