### ISSUE TITLE
attach_dispositions are ignored

### ISSUE THREAD

**Issue by SergiyIurenko** [rich-iannone/blastula#56]
Call to send_email_out with attach_dispositions argument supplied do not generate correct command line for mailsend:
```
send_email_out(
  message = ml,
  from = "my@mail.com",
  to = "my@mail.com",
  subject = "Test mail",
  creds_file = ".email_test",
  sender = "Test",
  attachments = c("/home/ruser/somedir/temp.html"),
  attach_dispositions = c("attachment","attachment"),
  verbose = T,
  debug=T
)
```
Mailsend command generated as follow:
```
/home/ruser/somedir/mailsend -from "my@mail.com" -name "Test" -t "my@mail.com" +cc +bc -sub "Test mail" -ssl   -smtp smtp.gmail.com -port 465 -auth -user my@mail.com -pass "hashedpasswordhere" -v -mime-type "text/html" -enc-type "us-ascii" -disposition "inline" -attach "message_inlined.html" -attach /home/ruser/somedir/temp.html
```
As we see for the attachment `temp.html` flag -disposition "attachment" was not generated and thus this attachment use previously supplied flag related to message body. This is incorrect.

**Comment by rich-iannone** [comment]
@SergiyIurenko  Please have a look at a temporary workaround (which is to become a permanent solution) in https://github.com/rich-iannone/blastula/issues/87.
