### ISSUE TITLE
plots in `gt` tables disappear on send

### ISSUE THREAD

**Issue by GregSutcliffe** [rich-iannone/blastula#58]
I'm using [this example](https://github.com/rstudio/gt/issues/152) to render `ggplot` sparklines in a `gt` table, and then trying to send that table via `blastula`.

The table renders fine in RStudio, as does an email object containing it, e.g:
```
email_text <-
  "
Here's the table

{as_raw_html(my_gt_table)}
"

email_object <-
  compose_email(
    body = email_text)

print(email_object)
```
The viewer pane will correctly show the sparklines. However, when I call `smtp_send()` with my GMail credentials, the resulting email does not display the plots - the column is blank.

I'm sure I'm just doing something stupid, any debugging tips?

**Comment by GregSutcliffe** [comment]
Update, the HTML file I saved from the RStudio preview pane worked fine for me, but did not render for my colleague who I sent it to - so now I'm suspecting browser issues. Is there a good way of sending table/plot data with Blastula?

**Comment by rich-iannone** [comment]
This is an issue where we need to build functionality for deploying images to some sort of CDN. We can do this manually right now with the `add_imgur_image()` but I think we'd want a more automatic solution than that. This issue (https://github.com/rich-iannone/blastula/issues/46) has some ideas on this.

**Comment by rich-iannone** [comment]
@GregSutcliffe  Please have a look at a temporary workaround (which is to become a permanent solution) in https://github.com/rich-iannone/blastula/issues/87.

**Comment by GregSutcliffe** [comment]
Thanks @rich-iannone!

I've had a play with the new branch on Blastula, looks nice - I can confirm the simple example of sending a single plot works for me. Bravo :)

However, I'm unclear on how to apply this to GT with embedded images. I have a working GT table, ~20 rows, each with a sparkline plot in the last column, like this:

![2019-10-30-111523_1873x575_scrot](https://user-images.githubusercontent.com/827786/67853529-a3eb6780-fb06-11e9-8e79-bde805d0a2c7.png)

That is saved as object `events`, so how would I embed this in the compose email call? If I use:
```
email_object <-
  compose_email(
    body = md(c(
      "Here's the table below:
      ",
      events,
      "Cheers"
    )),
    footer =
      "Email sent on {current_date_time}."
  )
```
Then all I get is a page of HTML in my email, rather than a table. If I instead use `as_raw_html(events)` in the above block, then I *do* get the table - but the images are gone.

Am I missing something? Or is the usecase for GT simply not ready for use yet (which would be fine, to be clear)?

**Comment by rich-iannone** [comment]
Would you able able to provide all the code for this? I can test it out and see what the problem is. What happens if you don’t include the sparkline column?

**Comment by rich-iannone** [comment]
In the `gt()` statement, I used:

```r
events <-
  new_events %>%
    left_join(past_events,by='name') %>%
    mutate(sparkline = plot %>% .[[1]] %>% ggplot_image(aspect_ratio = 2, height = 60)) %>%
    select(-plot) %>%
    gt() %>%
    fmt_markdown(columns = vars(sparkline)) %>%
    cols_label(
      sparkline = "RSVP history",
    ) %>%
    tab_options(
      table.width = pct(100)
    )
```

Which got me a table with a plot column. The next step is to use this:

```r
email_object <-
  compose_email(
    body = md(events %>% as_raw_html(inline_css = TRUE)),
    footer = "Yay"
  )
```

To get the email. The people seems to lie in **gt**'s `as_raw_html()` function because it currently strips out the Base64-encoded image. I'll post an issue in the **gt** repo for this.

**Comment by GregSutcliffe** [comment]
So to clarify, you're also seeing the problem in `email_object`? I still get a table without plots in the final column, even with your code for `email_object`, so if you're getting plots we're different somehow (that's with your changes to the `gt()` call, which is much cleaner, thanks!)

Assuming yes, then it looks like a case of waiting for that issue with `as_raw_html()` to be fixed. Thanks for your help so far!

**Comment by sunainakollu** [comment]
> So to clarify, you're also seeing the problem in `email_object`? I still get a table without plots in the final column, even with your code for `email_object` (which I think is the same as my second example), so if you're getting plots we're different somehow. That's with your changes to the `gt()` call, which is much cleaner, thanks!
> 
> Assuming yes, then it looks like a case of waiting for that issue with `as_raw_html()` to be fixed. Thanks for your help so far!

Not sure if it helps you now. I had the same issue and the ggplots would not render in the gt table in the email. I used print() instead of as_raw_html() and it worked.

**Comment by skr5k** [comment]
hi,
i ran into the same exact issue. to me it rather seems that `gt::as_raw_html()` is not the culprit, my html code as returned by `gt::as_raw_html()` still renders well when I manually save the code as an html file and display it in my browser. the svg charts disappear though, when I use `blastula::md()` (still saving as separate html file). Trying to cheat `blastula::compose_email()` and sending the raw html into the body doesnt work though either, so something in `blastula::compose_email()` seems to remove/disable stuff in the process of `process_markdown(body)` I suspect...
