### ISSUE TITLE
Subject line in RSC-RMarkdown emailing

### ISSUE THREAD

**Issue by rich-iannone** [rich-iannone/blastula#59]
Currently the subject line for an email message from an RSC-RMarkdown process is contained in the YAML front matter of the main .Rmd document as:

````
---
...
rmd_output_metadata:
  rsc_email_subject: Subject of Email
...
---
````

The subject of the email really shouldn't live here, it should reside in the email .Rmd document. Further to this, the function call that renders an email (`render_email()`) should have a `subject` argument that overrides the same in the YAML.

cc: @slopp

**Comment by slopp** [comment]
I was actually thinking this would be an argument to `attach_email`? But I could see it going either way. 

I was thinking `render_email` deals with what the body of the email looks like, whereas `attach_email` deals with how it is sent. But this boundary could be debated :) 

Either way, it would also be great if the subject line was displayed in the email preview somehow. Perhaps in the message included at the top of the preview:

<img width="599" alt="Screen Shot 2019-07-25 at 11 19 03 AM" src="https://user-images.githubusercontent.com/15901072/61894767-51c6f480-aece-11e9-8814-bc177b947283.png">

**Comment by rich-iannone** [comment]
@slopp Given that `render_email()` and `attach_email()` are both RSC-specific, do you think it might be better to rename these as `rsc_render_email()` and `rsc_attach_email()`? Might be good for tab completion and anybody not using Connect will just know to steer clear of these functions.

**Comment by slopp** [comment]
That is fine with me Rich, though doesn't `render_email` do something useful outside of the RSC context? I though `attach_email` was really the RSC-specific one, but I could be misunderstanding.
