### ISSUE TITLE
Aligning emails body

### ISSUE THREAD

**Issue by AlexanderMedvedevskikh** [rich-iannone/blastula#6]
Hi, many thanks for great R package!

I am using smtp.office365.com as the SMTP
When I opening emails in Outlook the email body is right aligned.
When I using Office365 (https://smtp.office365.com/owa/) the email body is center aligned.

1. How can I make the emails center aligned in Outlook?
2. How to resize container of the email body (increase width)?

![outlook_](https://user-images.githubusercontent.com/10042245/31338869-5cf30860-ad1a-11e7-9252-ab5d29134e1f.png)
![office365_](https://user-images.githubusercontent.com/10042245/31338876-60329d2e-ad1a-11e7-8345-3bf5cbae2cb7.png)

**Comment by shrektan** [comment]
Yes I encounter the same issue. The email view works perfect on my iPhone but not on Office 2010 - Outlook. The body is always right aligned and in order to see the picture I have to click "view it in the web browser".
