### ISSUE TITLE
Email attachments in RSC-RMarkdown emailing

### ISSUE THREAD

**Issue by rich-iannone** [rich-iannone/blastula#60]
Currently, there is no way to specify email attachments for an email message produced in an RSC-RMarkdown process. We would need an `attachments` argument in either `attach_email()` or `render_email()` to express which files are attached to the RSC email message.

Also, it would be nice to programmatically express email attachments. Files can come from various locations (e.g., already available in RSC, produced as part of .Rmd render process, local files on user's system, etc.). It would be useful to have a function (not part of the **blastula** package) that allows users to search for files and return a vector of matches (which could be part of the input for the `attachments` arg).

cc: @slopp

**Comment by slopp** [comment]
One other thing to keep in mind, RStudio Connect sets a "default" attachment, see: 

https://docs.rstudio.com/connect/user/r-markdown.html#r-markdown-email-suppress-report-attachment

I could see this being implemented as:

```
blastula::attach_email(
      email = render_email('email.Rmd'), 
      attachments = c("test.csv", "default")
)
```

Where `default` has a special meaning and indicates whether or not the actual report should be attached.

**Comment by slopp** [comment]
It would be great if the browser generated preview included a list of what would be attached. This could be added here:

<img width="599" alt="Screen Shot 2019-07-25 at 11 19 03 AM" src="https://user-images.githubusercontent.com/15901072/61894609-0d3b5900-aece-11e9-9a44-6f8abb0c6486.png">
