### ISSUE TITLE
Getting System command error on R 3.6.1 and windows 10

### ISSUE THREAD

**Issue by Salkon-data** [rich-iannone/blastula#63]
Hello,

I'm trying to send an email using 

email_object%>% #email is done though compose_email()
smtp_send(from = "******@gmail.com",
          to = "*****@*****.fr",
          subject ="Test email",
          credentials = creds_key("gmail")) # I used create_smtp_creds_key() for that

But I'm having this error : 
Error in processx::run(command = binary_loc, args = run_args) : 
  System command error

I activated less secure apps on my gmail account and mailsend-go.exe is in my R working directory.

Here's my session_info : 

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keyring_1.1.0  blastula_0.2.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       tidyr_0.8.3      ps_1.3.0         crayon_1.3.4     dplyr_0.8.3      assertthat_0.2.1 R6_2.4.0         jsonlite_1.6    
 [9] magrittr_1.5     pillar_1.4.2     stringi_1.4.3    rlang_0.4.0      rstudioapi_0.10  tools_3.6.1      glue_1.3.1       purrr_0.3.2 

Thanks,
Alexandre.

**Comment by ChuliangXiao** [comment]
I am having the same error with creds file generated by `create_smtp_creds_file()` on Windows 10/R 3.6.0.

**Comment by matbmeijer** [comment]
Hi Richard, I believe the problem originates from using processx::run in Windows 10 by using the oldfashioned system2 - somehow processx::run did not work for me in windows 10 in any way. This may help as a solution. Regards

**Comment by MislavSag** [comment]
Maybe my error is connected with this one:

```
email_obj %>% smtp_send(
  from = "mislav.sagovac@contentio.biz",
  to = "kontakt@contentio.biz",
  subject = "Some subject",
  credentials = creds(
    user = "mislav.sagovac@contentio.biz", 
    provider = "outlook",
    sender_name = "Contentio",
    host = "mail.contentio.biz", 
    port = 25, 
    use_ssl = FALSE
  )
)
```
It returns:
```
Error in rethrow_call(c_processx_exec, command, c(command, args), stdin,  : 
  Command not found @win/processx.c:977
```

**Comment by rich-iannone** [comment]
@matbmeijer so, any examples you might try with `processx::run()` don’t work for you? If this is true for and the others here, then I’d want to (quickly) find some replacement method.

**Comment by matbmeijer** [comment]
Hi Richard,
I actually tested your question, and indeed processx::run works. Yet I always got the problem with 
blastula::smtp_send() at the following line. Replacing it with system2 made it work.
```r
send_result <- processx::run(command = binary_loc, args = run_args)
```
Yet when testing processx::run() with a simple case, it works for me:
```r
base<-system2(command='cmd',args = c("cd", normalizePath(getwd())), stdout = TRUE) 
package<-processx::run('cmd',args = c("cd", normalizePath(getwd())))

print(base)
[1] "Microsoft Windows [Version 10.0.18362.30]"           
[2] "(c) 2019 Microsoft Corporation. All rights reserved."
[3] ""                                                    
[4] "C:\\Users\\03739660\\Documents>"

print(package)
$status
[1] 0

$stdout
[1] "Microsoft Windows [Version 10.0.18362.30]\r\n(c) 2019 Microsoft Corporation. All rights reserved.\r\n\r\nC:\\Users\\03739660\\Documents>"

$stderr
[1] ""

$timeout
[1] FALSE
```
I will try to dig deeper why it does not work. But my evaluation was incorrect, processx runs in R for Windows 10, it has to do with the command

**Comment by MislavSag** [comment]
For me, it is working if I set `use_ssl` argument to `FALSE`. If I set it to true it returns an error:
```
Error in processx::run(command = binary_loc, args = run_args) : 
  System command error
```

**Comment by bennlich** [comment]
@matbmeijer I started a PR that should print a more specific error message than `System command error`: https://github.com/rich-iannone/blastula/pull/71

**Comment by rich-iannone** [comment]
@Salkon-data @ChuliangXiao @matbmeijer @MislavSag Please have a look at a temporary workaround (which is to become a permanent solution) in https://github.com/rich-iannone/blastula/issues/87.
