### ISSUE TITLE
Have smtp_send return a status code

### ISSUE THREAD

**Issue by fmichonneau** [rich-iannone/blastula#69]
could `smtp_send` return (invisibly) the status code or a logical to indicate the email was sent successfully. Currently, the function returns `NULL` regardless of the outcome.

**Comment by rich-iannone** [comment]
Good idea. I think a logical value would work best as the return value.

**Comment by rich-iannone** [comment]
@fmichonneau  This is being changed in https://github.com/rich-iannone/blastula/issues/87, where the **curl** package will be used to send an RFC-2822 message. The SMTP status code will be given if it isn't `250` (where mailing is unsuccessful for some reason).

**Comment by fmichonneau** [comment]
That sounds good. The curl approach seems very promising and interesting. Looking forward to testing/using it!

**Comment by rich-iannone** [comment]
The changes mentioned before are now merged in `master`. Closing.
