### ISSUE TITLE
Support a `password` argument in `creds`

### ISSUE THREAD

**Issue by bennlich** [rich-iannone/blastula#70]
I'd like to send e-mails programmatically, with no interactive password entry. Something like:
```
blastula::smtp_send(
  email = email,
  from = from,
  to = to,
  subject = subject,
  credentials = blastula::creds(
    host = smtp_host,
    port = smtp_port,
    user = smtp_user,
    password = smtp_password
  )
)
```
I'm not really interested in blastula's credential storage helpers. I'd like to store my credentials on my own. So I'd love it if `creds()` supported a password argument.

**Comment by rich-iannone** [comment]
Thank you for the issue and PR. We will review the PR pretty soon!

**Comment by rich-iannone** [comment]
Closing this because the PR was closed. See https://github.com/rich-iannone/blastula/pull/72 for details.
