### ISSUE TITLE
blast_first error

### ISSUE THREAD

**Issue by LiNk-NY** [rich-iannone/blastula#74]
Hi Rich, @rich-iannone 
I'm getting an error when running `blast_first`. 
```r
> blast_first()
Error in download.file(url, method = method, ...) : 
  cannot open URL 'https://raw.githubusercontent.com/rich-iannone/blastula/master/inst/linux/mailsend'
In addition: Warning message:
In download.file(url, method = method, ...) :
  cannot open URL 'https://raw.githubusercontent.com/rich-iannone/blastula/master/inst/linux/mailsend': HTTP status was '404 Not Found'
> packageVersion("blastula")
[1] '0.2.1'
```
Best, 
Marcel

**Comment by rich-iannone** [comment]
The reason for this is that we are transitioning phase where we won't longer use the `mailsend` binary (which `blast_first()` fetches for you) and we'll instead use the `mailsend-go` binary (which you're expected to install yourself).

If you get the dev version of **blastula** using `devtools::install_github()` and follow the instructions for getting `mailsend-go` (in the pkgdown site for the package), you can use the new `smtp_send()` function to send email.
