### ISSUE TITLE
All content of email is a child of a <p> tag

### ISSUE THREAD

**Issue by fmichonneau** [rich-iannone/blastula#77]
This call:

```r
test_simple <- compose_email(body = "A simple sentence")
```

produces the corresponding HTML:

```xml
...
<tr>
<td style="font-family: Helvetica, sans-serif; font-size: 14px; vertical-align: top;">
<p style="font-family: Helvetica, sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 16px;"><p>A simple sentence</p></p>
</td>
</tr>
...
```

If the email is more complex, for instance:

```r
more_complex <- compose_email(body = "## A header \n A sentence \n ## An image \n ![a cat](https://i.imgur.com/PcrZj3N.jpg)")
```

it produces:

```xml
...
<tr>
<td style="font-family: Helvetica, sans-serif; font-size: 14px; vertical-align: top;">
<p style="font-family: Helvetica, sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 16px;"><h2>A header</h2><p>A sentence</p><h2>An image</h2><p><img src="https://i.imgur.com/PcrZj3N.jpg" alt="a cat" /></p></p>
</td>
</tr>
...
```

Here the HTML is invalid as `<h2>` can't be a child of a `<p>`.

I identified 2 places in the code where this could be addressed:
- https://github.com/rich-iannone/blastula/blob/master/inst/rmd/template.html#L99
- https://github.com/rich-iannone/blastula/blob/master/R/compose_email.R#L260

and I haven't tried blocks yet so I don't know if this needs to be modified here as well:
- https://github.com/rich-iannone/blastula/blob/master/R/block_text.R#L77

I was going to put in a PR but I wasn't sure if the inline styling elements were needed and whether the `<p>` would need to be replaced with a `<div>` or if they could simply be removed.

**Comment by rich-iannone** [comment]
Thanks, François. I will experiment with this idea by using a `<div>` and viewing the test emails in a few clients.
