### ISSUE TITLE
Couldn't find smtp_send function even after installation

### ISSUE THREAD

**Issue by nalsha** [rich-iannone/blastula#89]
R studio cannot find smtp_send function despite installation of blastula .

Error: 'smtp_send' is not an exported object from 'namespace:blastula'

Installed through
install.packages("devtools")
devtools::install_github("rich-iannone/blastula")
email <- blastula::compose_email(body = "Hello")
email %>% blastula::preview_email()
create_email_creds_file(
  user = "xyz@companyname.com",
  password = "xxxxxx",
  host = "xxxx",
  sender = "nalsha",
  provider = "outlook",
  creds_file_name = "creds")

 smtp_send(
  message = email,
  from = "xxx@companyname.com",
  to = "xxx@companyname.com",
  subject = "This is NOT junk mail.",
  creds_file = "creds", binary_loc = "C:\\Users\\nalsha\\Downloads\\mailsend-go_1.0.3_windows_64-bit\\mailsend-go-dir\\mailsend-go.exe")

**Comment by rich-iannone** [comment]
@nalsha Please have a look at a temporary workaround (which is to become a permanent solution) in https://github.com/rich-iannone/blastula/issues/87.
