### ISSUE TITLE
send_email_out giving error

### ISSUE THREAD

**Issue by nalsha** [rich-iannone/blastula#90]
Send_email_out is giving the following error:

"Error in download.file(url, method = method, ...) : 
  cannot open URL 'https://raw.githubusercontent.com/rich-iannone/blastula/master/inst/win/mailsend'"

install.packages("devtools")
devtools::install_github("rich-iannone/blastula")
email <- blastula::compose_email(body = "Hello")
email %>% blastula::preview_email()
create_email_creds_file(
user = "xyz@companyname.com",
password = "xxxxxx",
host = "xxxx",
sender = "nalsha",
provider = "outlook",
creds_file_name = "creds")

send_email_out(
message = email,
from = "xxx@companyname.com",
to = "xxx@companyname.com",
subject = "This is NOT junk mail.",
creds_file = "creds")

**Comment by lwjohnst86** [comment]
I have a similar issue, except is says "master/inst/linux/mailsend" for me.

**Comment by aaron-horowitz** [comment]
experiencing the same problem as @lwjohnst86 on linux

**Comment by rich-iannone** [comment]
@nalsha @lwjohnst86 @aaron-horowitz Please have a look at a temporary workaround (which is to become a permanent solution) in https://github.com/rich-iannone/blastula/issues/87.
