### ISSUE TITLE
Unable to use smtp_send without credentials

### ISSUE THREAD

**Issue by kaushiklakshman** [rich-iannone/blastula#91]
Hi I'm trying to use `smtp_send` to test the package using the following command 
```
test_message %>%
  smtp_send(
    from = "my.user@myorg.com.au",
    to = "my.user@myorg.com.au",
    subject = "Testing the `smtp_send()` function",
    credentials = creds_anonymous(
      host = "mail.myorg.com.au",
	  port = 25,
	  use_ssl = FALSE
    )
  )
```
 but I was constantly getting the following error
 ```
Error in processx::run(command = binary_loc, args = run_args) : 
  System command error 
```

When I tried the echo = TRUE command it gave the below command 

```
The command for sending the email message is:

c:/Workspace/mailsend-go.exe -sub Testing the `smtp_send()` function -smtp mail.myorg.com.au -port 25 -ssl auth -user anonymous -pass ***** my.user@myorg.com.au -to my.user@myorg.com.au attach -file C:/Users/myuser/AppData/Local/Temp/RtmpI1QH8N/file12f87a975cba.html -mime-type text/html -inline
```

However when I run the `mailsend-go.exe` from the windows command line using the following command it works just fine 
```
mailsend-go.exe -sub Testing -smtp mail.myorg.com.au -port 25 -to my.user@myorg.com.au -from my.user@myorg.com.au
```
I get the same error when I try to create a key using `create_smtp_creds_key` and use the `creds_key()` function 

Is there a way I can override the user & pass command to not be created, which seems to be the obstacle every time i pass a credential through?  Thanks!

**Comment by rich-iannone** [comment]
@nalsha Please have a look at a temporary workaround (which is to become a permanent solution) in https://github.com/rich-iannone/blastula/issues/87.
