### ISSUE TITLE
`smtp_send` throws an error at curl_fetch_memory in Office365

### ISSUE THREAD

**Issue by Aarleks** [rich-iannone/blastula#98]
Using Blastula 0.2.99.9

`smtp_send` run as per example:

```
create_smtp_creds_file(
  file = "email_creds",
  user = "idnumber@begoodtoyourmum.edu.au",
  provider = "office365"
)

test_message <- prepare_test_message()

test_message %>%
  smtp_send(
    from = "name@begoodtoyourmum.edu.au",
    to = "chum@gmail.com",
    subject = "Testing the `smtp_send()` function",
    credentials = creds_file(file = "email_creds")
  )
```
This returns the following error:
```
Error in curl::curl_fetch_memory(url, handle = h) : MAIL failed: 530
```
The same functions and message sent from a gmail account work fine, so seems related to Office365.

**Comment by Aarleks** [comment]
Ok, some further investigation this morning reveals that the following successfully sends the email:
```{r }
smtp_send(
    from = "name@begoodtoyourmum.edu.au",
    to = "chum@gmail.com",
    subject = "Testing the `smtp_send()` function",
    credentials = creds(
      user = "id@begoodtoyourmum.edu.au",
      provider = "office365",
    )
)
```
However, the resulting email has the same formatting problem as  #93 in terms of formatting (though with a cyan background and a 16 character column width)

**Comment by rich-iannone** [comment]
@Aarleks Thanks for the report here. Sorry about the display issue. I'll close this issue but could you add a screenshot to #93 ?

**Comment by Aarleks** [comment]
It's an interesting problem for me - mutt and curl in the shell work fine with the same settings. Much reading and learning has been done, but unfortunately I'm still not able to use Blastula like I did before. I'm sure it will be fixed soon and I'm sorry I haven't actually added anything of substantive help. I'm open to suggestions if you need help, though.

I'll post a screenshot to #93 now.

**Comment by Aarleks** [comment]
@rich-iannone It's an interesting problem for me - mutt and curl in the shell work fine with the same settings. Much reading and learning has been done, but unfortunately I'm still not able to use Blastula like I did before. I'm sure it will be fixed soon and I'm sorry I haven't actually added anything of substantive help. I'm open to suggestions if you need help, though.

I'll post a screenshot to #93 now.
